version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fireart_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fireart_db
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - APP_NAME=${APP_NAME:-NestJS App}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN:-3600}
      - RESET_TOKEN_SECRET=${RESET_TOKEN_SECRET}
      - RESET_TOKEN_EXPIRES_IN=${RESET_TOKEN_EXPIRES_IN:-3600}
      - SALT_ROUNDS=${SALT_ROUNDS:-10}
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
